# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1910f930788f5c80047d3d041fb4a1783771b3c5c3ce2cff136f8aa2dae13fcc13af86ed7bb42934c1a108359610517afa116a20b7523214aecd01e3ebf31b5

test:
  secret_key_base: 4a77de198c36b2c323c62ed194d638f6e0bea24f638748c7a34d68a86a03c474678b73f3e4f21c76bd005bb2fc3627a6d9186d64afc00dbd4f6096debf89d74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
